# -*- coding: utf-8 -*-
"""image _text to docs_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHMA1EQkxiZ3Zcj0Hl2yZ3ALMi3re3ZZ
"""

pip install easyocr python-docx

import easyocr
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from PIL import Image
import pytesseract

# Function to perform OCR using EasyOCR
def ocr_image(image_path):
    # Initialize EasyOCR with English language (you can specify other languages if needed)
    reader = easyocr.Reader(['en'])

    # Read the image and perform OCR
    result = reader.readtext(image_path)

    # Extract recognized text from the result
    recognized_text = '\n'.join([entry[1] for entry in result])

    return recognized_text

# Function to create a Word document and save the recognized text
def create_word_document(text, output_path):
    doc = Document()

    # Add text to the document
    paragraph = doc.add_paragraph()
    run = paragraph.add_run(text)

    # Set font size and alignment
    font = run.font
    font.size = Pt(12)
    paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT

    # Save the document
    doc.save(output_path)
    print(f"Word document saved at: {output_path}")

# Main function
def main():
    # Path to the handwritten text image
    image_path = '/content/download.png'

    # Perform OCR on the image using EasyOCR
    recognized_text = ocr_image(image_path)

    # Output file path for the Word document
    output_path = 'text.docx'

    # Create Word document with the recognized text
    create_word_document(recognized_text, output_path)

if __name__ == "__main__":
    main()

